### ISSUE TITLE
Error at launch (undefined symbol: _ZTI9QGtkStyle)

### ISSUE THREAD

**Issue by enguerran-popup** [LordAmit/Brightness#105]
Hello

I got this error when I try to launch `brightness-controller` : 
```
Traceback (most recent call last):
  File "/usr/share/brightness-controller/init.py", line 21, in <module>
    from PySide import QtGui, QtCore
ImportError: /usr/lib/python2.7/dist-packages/PySide/QtGui.so: undefined symbol: _ZTI9QGtkStyle
```

---
OS: Linux Mint 18.3 Cinnamon (based on Ubuntu Xenial)
Version of Brightness Controller: 2.0.2 (ppa)

<details> 
  <summary>output of `xrandr -q` (Click to show)</summary>

```
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
HDMI-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 381mm x 214mm
   1920x1080     60.01*+  59.93    40.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1280x1024     60.02  
   1440x900      59.89  
   1280x960      60.00  
   1360x768      59.80    59.96  
   1152x864      60.00  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   960x600       60.00  
   960x540       59.99  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   800x512       60.17  
   700x525       59.98  
   640x512       60.02  
   720x450       59.89  
   640x480       60.00    59.94  
   680x384       59.80    59.96  
   576x432       60.06  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
  1680x1050 (0x48) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x4c) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1024x768 (0x53) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x5a) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  640x480 (0x63) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz
```
</details>

**Comment by LordAmit** [comment]
Hmm, seems like your PySide package is somehow broken?

What happens when you open terminal, type `python`, and then enter the following command:

`from PySide import *`

**Comment by enguerran-popup** [comment]
I got the same error message

```
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PySide import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python2.7/dist-packages/PySide/QtGui.so: undefined symbol: _ZTI9QGtkStyle
```

I reinstalled all my pyside packages but it didn't fix it.

Here's my `dpkg -l *pyside*` output if it helps (Click to show)

```
||/ Nom                                                   Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-================================================================================================================
ii  libpyside1.2:amd64                                    1.2.2-2build2                   amd64                           Python bindings for Qt 4 (base files)
ii  python-pyside                                         1.2.2-2build2                   all                             Python bindings for Qt4 (big metapackage)
ii  python-pyside.phonon                                  1.2.2-2build2                   amd64                           Qt 4 Phonon module - Python bindings
ii  python-pyside.qtcore                                  1.2.2-2build2                   amd64                           Qt 4 core module - Python bindings
ii  python-pyside.qtdeclarative                           1.2.2-2build2                   amd64                           Qt 4 Declarative module - Python bindings
ii  python-pyside.qtgui                                   1.2.2-2build2                   amd64                           Qt 4 GUI module - Python bindings
ii  python-pyside.qthelp                                  1.2.2-2build2                   amd64                           Qt 4 help module - Python bindings
ii  python-pyside.qtnetwork                               1.2.2-2build2                   amd64                           Qt 4 network module - Python bindings
ii  python-pyside.qtopengl                                1.2.2-2build2                   amd64                           Qt 4 OpenGL module - Python bindings
ii  python-pyside.qtscript                                1.2.2-2build2                   amd64                           Qt 4 script module - Python bindings
ii  python-pyside.qtsql                                   1.2.2-2build2                   amd64                           Qt 4 SQL module - Python bindings
ii  python-pyside.qtsvg                                   1.2.2-2build2                   amd64                           Qt 4 SVG module - Python bindings
ii  python-pyside.qttest                                  1.2.2-2build2                   amd64                           Qt 4 test module - Python bindings
ii  python-pyside.qtuitools                               1.2.2-2build2                   amd64                           Qt 4 UI tools module - Python bindings
ii  python-pyside.qtwebkit                                1.2.2-2build2                   amd64                           Qt 4 WebKit module - Python bindings
ii  python-pyside.qtxml                                   1.2.2-2build2                   amd64                           Qt 4 XML module - Python bindings
```

**Comment by LordAmit** [comment]
Hey, Seems like this is an error related to PyQT installation and I am not really sure how to solve it.

I went to google to search for it, but there was not any clear direction.

https://www.google.com/search?client=ubuntu&channel=fs&q=ImportError%3A+%2Fusr%2Flib%2Fpython2.7%2Fdist-packages%2FPySide%2FQtGui.so%3A+undefined+symbol%3A+_ZTI9QGtkStyle&ie=utf-8&oe=utf-8

**Comment by enguerran-popup** [comment]
After struggling with PySide (install via pip, manual build...). 
I ended up installing an applet that can do the same thing. https://cinnamon-spices.linuxmint.com/applets/view/286

Thanks for your help anyways ;)

**Comment by LordAmit** [comment]
Ah, Thanks for letting me know about it :smile: I am really sorry that a solution was not found; if I can find any, I will get back here and inform you under this issue.
