### ISSUE TITLE
Brightness-Controller doesnt work on HDMI

### ISSUE THREAD

**Issue by IAMtheIAM** [LordAmit/Brightness#111]
OS:  Linux mint 19
Distro: 
output of `xrandr -q`
```
Screen 0: minimum 8 x 8, current 6880 x 2560, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 2560x1440+1440+160 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   1920x1080     60.00    59.94    50.00    29.97    25.00    23.98    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 connected 1440x2560+0+0 left (normal left inverted right x axis y axis) 597mm x 336mm
   3840x2160     60.00 +  29.98  
   2560x1440     59.95* 
   1920x1200     59.88  
   1920x1080     60.00    59.94    50.00    23.98  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1440x2560+4000+0 left (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   3840x2160     29.97  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1680x1050     59.95  
   1600x900      60.00  
   1440x576      50.00  
   1440x480      59.94  
   1280x1440     59.90  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1440x2560+5440+0 right (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   3840x2160     29.97  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1680x1050     59.95  
   1600x900      60.00  
   1440x576      50.00  
   1440x480      59.94  
   1280x1440     59.90  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-5 disconnected (normal left inverted right x axis y axis)

```
Version of Brightness Controller: 
2.0 build 1

First of all, thanks, this is great. 
It works for any DisplayPort monitor. For any HDMI monitor I get errors like this;

```
warning: output None not found; ignoring
xrandr: Need crtc to set gamma on.
Traceback (most recent call last):
  File "/usr/share/brightness-controller/init.py", line 168, in change_value_pbr
    Executor.execute_command(cmd_value)
  File "/usr/share/brightness-controller/util/executor.py", line 23, in execute_command
    subprocess.check_output(string_cmd, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'xrandr        --output None         --brightness 0.99        --gamma 1.0:1.0:1.0' returned non-zero exit status 1

```

Is it HDMI compatible?

**Comment by LordAmit** [comment]
Umm, since the other issues did not get any response, I am assuming that this won't receive any either.

**Comment by IAMtheIAM** [comment]
Hmm, nevermind. I reinstalled again and now both primary and secondary work for DP and HDMI. Weird.

But, the new version only support 2 monitors, brightness-controller-simple didn't work. It says "primary, not found. secondary, not found"

**Comment by avidrucker** [comment]
I am experiencing the same issue. Please advise.
