### ISSUE TITLE
TypeError: 'Shiboken.ObjectType' object is not iterable

### ISSUE THREAD

**Issue by meeas** [LordAmit/Brightness#170]
Just installed your PPA for Groovy and app fails to launch:

Traceback (most recent call last):
  File "/usr/share/brightness-controller/init.py", line 30, in <module>
    import util.executor as Executor
  File "/usr/share/brightness-controller/util/executor.py", line 19, in <module>
    import subprocess
  File "/usr/lib/python3.8/subprocess.py", line 49, in <module>
    import signal
  File "/usr/lib/python3.8/signal.py", line 8, in <module>
    _IntEnum._convert_(
  File "/usr/lib/python3.8/enum.py", line 461, in _convert_
    cls = cls(name, members, module=module)
  File "/usr/lib/python3.8/enum.py", line 306, in __call__
    return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)
  File "/usr/lib/python3.8/enum.py", line 416, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/lib/python3.8/enum.py", line 164, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict)
TypeError: 'Shiboken.ObjectType' object is not iterable

I'm running a fully updated Debian Testing with Python 3.8.3rc1 and the following PySide packages:

python3-pyside2.qtcore is already the newest version (5.13.2-2.2+b2).
python3-pyside2.qtgui is already the newest version (5.13.2-2.2+b2).
python3-pyside2.qtnetwork is already the newest version (5.13.2-2.2+b2).
python3-pyside2.qtwidgets is already the newest version (5.13.2-2.2+b2).

**Comment by LordAmit** [comment]
Hi,

looks like it is due to API incompatibility between the python version being used and PySide2. My guess is that it is due to the release candidate version of python you are using. It can also be due to the version of PySide as suggested [here](https://bugreports.qt.io/browse/PYSIDE-1140)

For now, my recommendation is to try running it using Python3.7.
