### ISSUE TITLE
interrupted shutdown

### ISSUE THREAD

**Issue by ZhouChuang321** [LordAmit/Brightness#195]
**Describe the bug**
my system is Ubuntu 18.04
I can run the program from terminal
but once I pull the button of the brightness bar, the program will shut down interrupted 
and the terminal will show

chuang@Chuang:~/下载/Brightness-master/src$ python init.py
xrandr: Gamma size is 0.
Traceback (most recent call last):
  File "init.py", line 277, in change_value_pbr
    Executor.execute_command(cmd_value)
  File "/home/chuang/下载/Brightness-master/src/util/executor.py", line 23, in execute_command
    subprocess.check_output(string_cmd, shell=True)
  File "/home/chuang/anaconda3/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/home/chuang/anaconda3/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xrandr        --output default         --brightness 0.9900000000000007        --gamma 1.0000000000000007:1.0000000000000007:1.0000000000000007' returned non-zero exit status 1.
Aborted (core dumped)

**Comment by apandada1** [comment]
1. What is the output of `xrandr -q` ?
2. Can you change brightness with commands like `xrandr --output default --brightness 0.7` ?
