### ISSUE TITLE
Monitors default to "none"

### ISSUE THREAD

**Issue by codebling** [LordAmit/Brightness#205]
**Describe the bug**
Brightness Controller crashes
```
warning: output None not found; ignoring
xrandr: Need crtc to set gamma on.
Traceback (most recent call last):
  File "/usr/share/brightness-controller/init.py", line 277, in change_value_pbr
    Executor.execute_command(cmd_value)
  File "/usr/share/brightness-controller/util/executor.py", line 23, in execute_command
    subprocess.check_output(string_cmd, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'xrandr        --output None         --brightness 0.9900000000000007        --gamma 1.0000000000000007:1.0000000000000007:1.0000000000000007' returned non-zero exit status 1.
/usr/bin/brightness-controller: line 4: 22622 Aborted                 (core dumped) python init.py
```

The monitor/output shown appears to be correct. If I **reselect the same monitor that is already shown**, the program works as expected. It seems like this is just an issue with it defaulting to `None`. 

**To Reproduce**
1. Open Brightness Controller
2. Adjust brightness slider

**Expected behavior**
Brightness slider adjustment doesn't cause crash.

**Desktop (please complete the following information):**
 - OS: Arch 2022-04-14

**Comment by LordAmit** [comment]
Heyo, check #201.
